services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "42004:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./telemetry_server/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "42003:3000"
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_PLUGINS_ALLOW_UNSIGNED_PLUGINS=true
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=false

    volumes: # this is where it they get moved to in the CONTAINER
      - ./telemetry_server/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana  # where grafana stores its data
    depends_on:
      - prometheus

volumes:
  grafana_data:
  
# user: "admin", password: "rocket"