services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "42004:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "42003:3000"
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_PLUGINS_ALLOW_UNSIGNED_PLUGINS=true
      - GF_PLUGINS_PLUGIN_ADMIN_ENABLED=false

    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana_data:
  
