# Rotation Visualizer
ProxyPass /api/rotation/ http://127.0.0.1:5001/api/rotation/
ProxyPassReverse /api/rotation/ http://127.0.0.1:5001/api/rotation/


# Setlister
ProxyPass /api/setlister/ http://127.0.0.1:5702/api/setlister/
ProxyPassReverse /api/setlister/ http://127.0.0.1:5702/api/setlister/

# DataViz
ProxyPass /api/dataviz/ http://127.0.0.1:42000/api/v1/
ProxyPassReverse /api/dataviz/ http://127.0.0.1:42000/api/v1/
